/** Granular admin permissions (shared by server + admin UI). */
export const PERMISSIONS: { key: string; label: string; group: string }[] = [
  { key: "dashboard.view", label: "View dashboard", group: "Dashboard" },
  { key: "reports.view", label: "View financial reports", group: "Dashboard" },
  { key: "users.view", label: "View users", group: "Users" },
  { key: "users.edit", label: "Edit users", group: "Users" },
  { key: "users.suspend", label: "Suspend / ban users", group: "Users" },
  { key: "users.balance", label: "Adjust balances", group: "Users" },
  { key: "users.notes", label: "Internal user notes", group: "Users" },
  { key: "finance.view", label: "View deposits, withdrawals & ledger", group: "Finance" },
  { key: "finance.approve", label: "Approve / process payments", group: "Finance" },
  { key: "finance.reject", label: "Reject payments", group: "Finance" },
  { key: "finance.settings", label: "Manage payment methods, fees & limits", group: "Finance" },
  { key: "kyc.view", label: "View KYC submissions", group: "KYC" },
  { key: "kyc.review", label: "Review KYC", group: "KYC" },
  { key: "games.view", label: "View games", group: "Games" },
  { key: "games.create", label: "Create games", group: "Games" },
  { key: "games.edit", label: "Edit games, categories & providers", group: "Games" },
  { key: "games.delete", label: "Delete games", group: "Games" },
  { key: "bonuses.view", label: "View bonuses & promo codes", group: "Marketing" },
  { key: "bonuses.manage", label: "Manage bonuses, promo codes & VIP", group: "Marketing" },
  { key: "marketing.notifications", label: "Send notifications", group: "Marketing" },
  { key: "content.banners", label: "Manage banners", group: "Content" },
  { key: "content.promotions", label: "Manage promotions", group: "Content" },
  { key: "content.pages", label: "Manage CMS pages", group: "Content" },
  { key: "affiliates.view", label: "View referrals & agents", group: "Affiliates" },
  { key: "affiliates.manage", label: "Manage agents & commissions", group: "Affiliates" },
  { key: "support.view", label: "View support inbox", group: "Support" },
  { key: "support.reply", label: "Reply to tickets & chat", group: "Support" },
  { key: "support.assign", label: "Assign tickets", group: "Support" },
  { key: "roles.view", label: "View roles", group: "Access" },
  { key: "roles.manage", label: "Manage roles & permissions", group: "Access" },
  { key: "admins.manage", label: "Manage admin accounts", group: "Access" },
  { key: "settings.view", label: "View site settings", group: "Settings" },
  { key: "settings.edit", label: "Edit site settings & SEO", group: "Settings" },
  { key: "audit.view", label: "View audit log", group: "Settings" },
];

export const ROLE_PRESETS: { slug: string; name: string; description: string; perms: string[] }[] = [
  { slug: "super_admin", name: "Super Admin", description: "Full unrestricted access", perms: PERMISSIONS.map((p) => p.key) },
  {
    slug: "finance_manager",
    name: "Finance Manager",
    description: "Payments, ledger, KYC and reports",
    perms: ["dashboard.view", "reports.view", "users.view", "users.balance", "users.notes", "finance.view", "finance.approve", "finance.reject", "finance.settings", "kyc.view", "kyc.review", "affiliates.view", "affiliates.manage", "audit.view"],
  },
  { slug: "game_manager", name: "Game Manager", description: "Game catalog, categories and providers", perms: ["dashboard.view", "games.view", "games.create", "games.edit", "games.delete"] },
  {
    slug: "marketing_manager",
    name: "Marketing Manager",
    description: "Bonuses, promo codes, VIP, promotions and notifications",
    perms: ["dashboard.view", "users.view", "bonuses.view", "bonuses.manage", "marketing.notifications", "content.banners", "content.promotions", "affiliates.view", "affiliates.manage"],
  },
  { slug: "content_manager", name: "Content Manager", description: "Banners, promotions, CMS and SEO", perms: ["dashboard.view", "content.banners", "content.promotions", "content.pages", "settings.view"] },
  { slug: "support_manager", name: "Support Manager", description: "Support inbox, chat and KYC visibility", perms: ["dashboard.view", "users.view", "users.notes", "support.view", "support.reply", "support.assign", "kyc.view", "marketing.notifications"] },
  { slug: "moderator", name: "Moderator", description: "User moderation and first-line support", perms: ["dashboard.view", "users.view", "users.suspend", "users.notes", "support.view", "support.reply"] },
];
