"use client";

import { Boxes, ChevronRight, Gamepad2, LayoutGrid, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Modal } from "@/components/ui/Modal";
import { Card, Empty, Input, Pagination, Select, Spinner, Stat, StatusBadge, inputCls } from "@/components/ui/kit";
import { api, errMsg } from "@/lib/api";
import { RESOURCE_MAP } from "@/lib/admin/resources";
import { ResourceManager } from "./ResourceManager";
import { GameThumbnail } from "./GameThumbnail";
import { GameApiManagement } from "./GameApiManagement";
import type { AdminMe } from "./AdminApp";

type Tab = "overview" | "games" | "providers" | "categories" | "apis";
type Choice = { value: number | string; label: string };
type Category = { id: number; name: string; slug: string; color: string; isActive: boolean; gameCount?: number };
type Game = { id: number; name: string; slug: string; thumbnail: string | null; status: "active" | "inactive" | "maintenance"; providerId: number | null; providerName: string; apiSource: string | null; apiSourceName: string; apiExternalId: string | null; providerGameId: string; gameType: string | null; isFeatured: boolean; sortOrder: number; categoryIds: number[]; categoryNames: string[] };
type GameList = { items: Game[]; total: number; page: number; pageSize: number; providers: Choice[]; categories: Choice[]; apiSources: Choice[]; gameTypes: Choice[] };
type Summary = { total: number; active: number; inactive: number; providers: number; categories: number; gameApis: number };

const tabs: { id: Tab; label: string; icon: typeof Gamepad2 }[] = [
  { id: "overview", label: "Overview", icon: LayoutGrid },
  { id: "games", label: "All Games", icon: Gamepad2 },
  { id: "providers", label: "Providers", icon: Boxes },
  { id: "categories", label: "Categories", icon: LayoutGrid },
  { id: "apis", label: "Game APIs", icon: Gamepad2 },
];

export function GameManagement({ me }: { me: AdminMe }) {
  const section = useSearchParams().get("s");
  const initialTab: Tab = section === "games" ? "games" : section === "providers" ? "providers" : section === "categories" ? "categories" : ["aggregator", "custom-game-apis", "game-api-management"].includes(section ?? "") ? "apis" : "overview";
  const [tab, setTab] = useState<Tab>(initialTab);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [refresh, setRefresh] = useState(0);
  const reloadSummary = useCallback(() => api<Summary>("/api/admin/game-management/summary").then(setSummary).catch(() => setSummary(null)), []);
  useEffect(() => { reloadSummary(); }, [reloadSummary, refresh]);
  return <div className="space-y-5">
    <div className="flex flex-wrap gap-2 border-b border-white/10 pb-3">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-2 rounded-xl px-3 py-2 text-[13px] font-medium ${tab === id ? "bg-gold-300/15 text-gold-200" : "text-white/55 hover:bg-white/5 hover:text-white"}`}><Icon className="h-4 w-4" />{label}</button>)}</div>
    {tab === "overview" && <Overview summary={summary} onOpen={setTab} />}
    {tab === "games" && <GamesView key={`games-${refresh}`} onChanged={() => setRefresh((n) => n + 1)} />}
    {tab === "providers" && <ResourceManager resource={RESOURCE_MAP.providers} me={me} />}
    {tab === "categories" && <CategoriesView key={`categories-${refresh}`} onChanged={() => setRefresh((n) => n + 1)} />}
    {tab === "apis" && <GameApiManagement />}
  </div>;
}

function Overview({ summary, onOpen }: { summary: Summary | null; onOpen: (tab: Tab) => void }) {
  return <div className="space-y-5"><div><h2 className="font-display text-2xl font-semibold text-white">Game Management</h2><p className="mt-1 text-sm text-white/50">Manage your catalog, providers, categories, and connected game APIs.</p></div>
    <div className="grid grid-cols-2 gap-3 xl:grid-cols-6">{[["Total Games", summary?.total], ["Active", summary?.active], ["Inactive", summary?.inactive], ["Providers", summary?.providers], ["Categories", summary?.categories], ["Game APIs", summary?.gameApis]].map(([label, value]) => <Stat key={String(label)} label={String(label)} value={value == null ? "—" : Number(value).toLocaleString()} />)}</div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{tabs.filter((t) => t.id !== "overview").map(({ id, label, icon: Icon }) => <button key={id} onClick={() => onOpen(id)} className="panel flex items-center justify-between rounded-2xl p-4 text-left hover:border-gold-300/30"><span className="flex items-center gap-3"><Icon className="h-5 w-5 text-gold-300" /><span className="font-medium text-white">{label}</span></span><ChevronRight className="h-4 w-4 text-white/40" /></button>)}</div>
  </div>;
}

function GamesView({ onChanged }: { onChanged: () => void }) {
  const [q, setQ] = useState(""); const [providerId, setProviderId] = useState(""); const [apiSource, setApiSource] = useState(""); const [categoryId, setCategoryId] = useState(""); const [status, setStatus] = useState(""); const [gameType, setGameType] = useState(""); const [page, setPage] = useState(1); const [data, setData] = useState<GameList | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [selected, setSelected] = useState<number[]>([]); const [edit, setEdit] = useState<Game | null>(null); const [categoryAction, setCategoryAction] = useState<"add" | "remove">("add"); const [bulkCategory, setBulkCategory] = useState("");
  const load = useCallback(async () => { setError(""); try { const params = new URLSearchParams({ q, page: String(page), pageSize: "50" }); if (providerId) params.set("providerId", providerId); if (apiSource) params.set("apiSource", apiSource); if (categoryId) params.set("categoryId", categoryId); if (status) params.set("status", status); if (gameType) params.set("gameType", gameType); setData(await api<GameList>(`/api/admin/game-management/games?${params}`)); } catch (e) { setError(errMsg(e)); } }, [q, page, providerId, apiSource, categoryId, status, gameType]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  useEffect(() => setSelected([]), [q, page, providerId, apiSource, categoryId, status, gameType]);
  const mutateGame = async (game: Game, body: Record<string, unknown>) => { setBusy(true); try { await api(`/api/admin/game-management/games/${game.id}`, { method: "PATCH", body }); await load(); onChanged(); } catch (e) { setError(errMsg(e)); } finally { setBusy(false); } };
  const removeGame = async (game: Game) => { if (!confirm(`Delete “${game.name}”? This deletes the game only.`)) return; setBusy(true); try { await api(`/api/admin/game-management/games/${game.id}`, { method: "DELETE" }); await load(); onChanged(); } catch (e) { setError(errMsg(e)); } finally { setBusy(false); } };
  const bulk = async (action: "add" | "remove" | "activate" | "deactivate" | "delete") => {
    if (!selected.length) return;
    if (action === "add" || action === "remove") { if (!bulkCategory) { setError("Choose a category first."); return; } setBusy(true); try { await api("/api/admin/game-management/games/categories", { body: { gameIds: selected, categoryId: Number(bulkCategory), action } }); setSelected([]); await load(); onChanged(); } catch (e) { setError(errMsg(e)); } finally { setBusy(false); } return; }
    if (action === "delete" && !confirm(`Delete ${selected.length} selected games?`)) return;
    setBusy(true); try { if (action === "delete") await Promise.all(selected.map((id) => api(`/api/admin/game-management/games/${id}`, { method: "DELETE" }))); else await Promise.all(selected.map((id) => api(`/api/admin/game-management/games/${id}`, { method: "PATCH", body: { status: action === "activate" ? "active" : "inactive" } }))); setSelected([]); await load(); onChanged(); } catch (e) { setError(errMsg(e)); } finally { setBusy(false); }
  };
  const toggleAll = () => setSelected(selected.length === (data?.items.length ?? 0) ? [] : data?.items.map((g) => g.id) ?? []);
  const options = data?.providers ?? [];
  return <div className="space-y-4"><Card title="All Games" action={<span className="text-xs text-white/45">{data?.total.toLocaleString() ?? "…"} games</span>}>
    <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-6"><div className="relative xl:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-white/35"/><input className={`${inputCls} pl-9`} placeholder="Search name, ID, provider…" value={q} onChange={(e) => {setQ(e.target.value);setPage(1);}} /></div>
      <Select aria-label="Provider" value={providerId} onChange={(e) => {setProviderId(e.target.value);setPage(1);}} options={[{value:"",label:"All providers"},...options]} />
      <Select aria-label="API source" value={apiSource} onChange={(e) => {setApiSource(e.target.value);setPage(1);}} options={[{value:"",label:"All APIs"},...(data?.apiSources??[])]} />
      <Select aria-label="Category" value={categoryId} onChange={(e) => {setCategoryId(e.target.value);setPage(1);}} options={[{value:"",label:"All categories"},...(data?.categories??[])]} />
      <Select aria-label="Status" value={status} onChange={(e) => {setStatus(e.target.value);setPage(1);}} options={[{value:"",label:"All statuses"},{value:"active",label:"Active"},{value:"inactive",label:"Inactive"},{value:"maintenance",label:"Maintenance"}]} />
    </div>
    <div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Select aria-label="Game type" value={gameType} onChange={(e) => {setGameType(e.target.value);setPage(1);}} options={[{value:"",label:"All game types"},...(data?.gameTypes??[])]} /><div className="flex gap-2"><Select aria-label="Category action" value={categoryAction} onChange={(e) => setCategoryAction(e.target.value as "add"|"remove")} options={[{value:"add",label:"Add to category"},{value:"remove",label:"Remove from category"}]} /><Select aria-label="Bulk category" value={bulkCategory} onChange={(e) => setBulkCategory(e.target.value)} options={[{value:"",label:"Choose category"},...(data?.categories??[])]} /><Button size="sm" disabled={busy||!selected.length} onClick={() => bulk(categoryAction)}>{categoryAction === "add" ? "Apply" : "Remove"}</Button></div></div>
    {selected.length > 0 && <div className="flex flex-wrap items-center gap-2 rounded-xl bg-white/[0.03] p-2 text-xs"><span className="mr-auto text-white/70">{selected.length} selected</span><Button size="xs" variant="outline" disabled={busy} onClick={() => bulk("activate")}>Activate</Button><Button size="xs" variant="outline" disabled={busy} onClick={() => bulk("deactivate")}>Deactivate</Button><Button size="xs" variant="outline" className="border-rose-400/30 text-rose-300" disabled={busy} onClick={() => bulk("delete")}>Delete</Button></div>}
    {error && <p className="text-sm text-rose-300">{error}</p>}
    {!data ? <Spinner/> : !data.items.length ? <Empty text="No games match these filters."/> : <>
      <div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[900px] text-left text-xs"><thead className="text-[10px] uppercase tracking-wider text-white/40"><tr>{["", "Game", "Provider", "API Source", "Categories", "Status", "Actions"].map((h,i)=><th key={i} className="px-3 py-3">{i===0?<input aria-label="Select page" type="checkbox" checked={data.items.length>0&&selected.length===data.items.length} onChange={toggleAll}/>:h}</th>)}</tr></thead><tbody className="divide-y divide-white/[0.05]">{data.items.map((g)=><tr key={g.id} className="text-white/75"><td className="px-3 py-2"><input aria-label={`Select ${g.name}`} type="checkbox" checked={selected.includes(g.id)} onChange={(e)=>setSelected(e.target.checked?[...selected,g.id]:selected.filter(id=>id!==g.id))}/></td><td className="px-3 py-2"><div className="flex items-center gap-2"><GameThumbnail src={g.thumbnail} name={g.name} className="h-10 w-10 rounded-lg object-cover" /><span><b className="block text-white">{g.name}</b><small className="text-white/40">{g.apiExternalId||g.providerGameId||g.slug}</small></span></div></td><td className="px-3 py-2">{g.providerName}</td><td className="px-3 py-2">{g.apiSourceName}</td><td className="max-w-48 px-3 py-2 text-white/55">{g.categoryNames.join(", ")||"—"}</td><td className="px-3 py-2"><StatusBadge status={g.status}/></td><td className="px-3 py-2"><div className="flex gap-1"><Button size="xs" variant="outline" onClick={()=>setEdit(g)}>Edit</Button><Button size="xs" variant="outline" onClick={()=>mutateGame(g,{status:g.status==="active"?"inactive":"active"})}>{g.status==="active"?"Disable":"Enable"}</Button><button aria-label={`Delete ${g.name}`} onClick={()=>removeGame(g)} className="rounded-lg p-2 text-white/50 hover:text-rose-300"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div>
      <div className="grid gap-2 md:hidden">{data.items.map((g)=><article key={g.id} className="rounded-xl border border-white/10 p-3"><div className="flex gap-3"><GameThumbnail src={g.thumbnail} name={g.name} className="h-16 w-16 rounded-lg object-cover" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="truncate text-white">{g.name}</b><input type="checkbox" aria-label={`Select ${g.name}`} checked={selected.includes(g.id)} onChange={(e)=>setSelected(e.target.checked?[...selected,g.id]:selected.filter(id=>id!==g.id))}/></div><p className="text-xs text-white/50">{g.providerName} · {g.apiSourceName}</p><div className="mt-1"><StatusBadge status={g.status}/></div><p className="mt-1 truncate text-[11px] text-white/40">{g.categoryNames.join(", ")||"No categories"}</p></div></div><div className="mt-3 flex gap-2"><Button size="xs" variant="outline" onClick={()=>setEdit(g)}>Edit</Button><Button size="xs" variant="outline" onClick={()=>mutateGame(g,{status:g.status==="active"?"inactive":"active"})}>{g.status==="active"?"Disable":"Enable"}</Button><Button size="xs" variant="outline" className="border-rose-400/30 text-rose-300" onClick={()=>removeGame(g)}>Delete</Button></div></article>)}</div>
      <Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={setPage}/>
    </>}
  </Card>
  <Modal open={!!edit} onClose={()=>setEdit(null)} label="Edit game"><GameEditor game={edit} onSave={async(body)=>{if(edit){await mutateGame(edit,body);setEdit(null);}}}/></Modal>
  </div>;
}

function GameEditor({game,onSave}:{game:Game|null;onSave:(body:Record<string,unknown>)=>Promise<void>}) { const [name,setName]=useState(game?.name??""); const [status,setStatus]=useState(game?.status??"active"); const [featured,setFeatured]=useState(Boolean(game?.isFeatured)); const [sortOrder,setSortOrder]=useState(String(game?.sortOrder??0)); return game?<div className="space-y-4 p-5"><h3 className="text-lg font-semibold text-white">{game.name}</h3><div className="grid gap-2 sm:grid-cols-2"><Input label="Game name" value={name} onChange={e=>setName(e.target.value)}/><Input label="External game ID" value={game.apiExternalId||game.providerGameId||""} readOnly/><Input label="Provider" value={game.providerName} readOnly/><Input label="API source" value={game.apiSourceName} readOnly/><Select label="Status" value={status} onChange={e=>setStatus(e.target.value as typeof status)} options={[{value:"active",label:"Active"},{value:"inactive",label:"Inactive"},{value:"maintenance",label:"Maintenance"}]}/><Input label="Display order" type="number" value={sortOrder} onChange={e=>setSortOrder(e.target.value)}/></div><label className="flex items-center gap-2 text-sm text-white/70"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/> Featured</label><Button onClick={()=>onSave({name,status,isFeatured:featured,sortOrder:Number(sortOrder)||0})}>Save changes</Button></div>:null; }

function CategoriesView({onChanged}:{onChanged:()=>void}) {
  const [items,setItems]=useState<Category[]>([]); const [q,setQ]=useState(""); const [edit,setEdit]=useState<Category|null|"new">(null); const [name,setName]=useState(""); const [slug,setSlug]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [detail,setDetail]=useState<Category|null>(null);
  const load=useCallback(async()=>{try{const r=await api<{items:Category[]}>(`/api/admin/game-management/categories?q=${encodeURIComponent(q)}&pageSize=100`);setItems(r.items);}catch(e){setError(errMsg(e));}},[q]); useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t);},[load]);
  const open=(item:Category|null|"new")=>{setEdit(item);setName(item&&item!=="new"?item.name:"");setSlug(item&&item!=="new"?item.slug:"");setError("");};
  const save=async()=>{setBusy(true);try{const body={name,slug:slug.trim()||undefined};if(edit&&edit!=="new")await api(`/api/admin/game-management/categories/${edit.id}`,{method:"PATCH",body});else await api("/api/admin/game-management/categories",{body});setEdit(null);await load();onChanged();}catch(e){setError(errMsg(e));}finally{setBusy(false);}};
  const remove=async(item:Category)=>{if(!confirm(`Delete category “${item.name}”? Games will stay in the catalog.`))return;try{await api(`/api/admin/game-management/categories/${item.id}`,{method:"DELETE"});await load();onChanged();}catch(e){setError(errMsg(e));}};
  return <div className="space-y-4"><Card title="Categories" action={<Button size="sm" iconLeft={<Plus className="h-4 w-4"/>} onClick={()=>open("new")}>Add Category</Button>}><div className="mb-4 flex gap-2"><Input aria-label="Search categories" placeholder="Search categories…" value={q} onChange={e=>setQ(e.target.value)}/></div>{error&&<p className="mb-3 text-sm text-rose-300">{error}</p>}{!items.length?<Empty text="No categories found."/>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-white/[0.02] p-4"><div className="flex items-start justify-between"><div><h3 className="text-lg font-semibold text-white">{item.name}</h3><p className="text-xs text-white/45">{item.gameCount?.toLocaleString()??0} games · {item.slug}</p></div><StatusBadge status={item.isActive?"active":"inactive"}/></div><div className="mt-4 flex flex-wrap gap-2"><Button size="xs" onClick={()=>setDetail(item)}>Open</Button><Button size="xs" variant="outline" onClick={()=>open(item)}>Edit</Button><Button size="xs" variant="outline" onClick={async()=>{try{await api(`/api/admin/game-management/categories/${item.id}`,{method:"PATCH",body:{isActive:!item.isActive}});await load();onChanged();}catch(e){setError(errMsg(e));}}}>{item.isActive?"Disable":"Enable"}</Button><button onClick={()=>remove(item)} aria-label={`Delete ${item.name}`} className="ml-auto rounded-lg border border-white/10 p-2 text-white/50 hover:text-rose-300"><Trash2 className="h-4 w-4"/></button></div></article>)}</div>}</Card>
    <Modal open={!!edit} onClose={()=>setEdit(null)} label="Edit category"><div className="space-y-3 p-5"><h3 className="text-lg font-semibold text-white">{edit==="new"?"Add category":"Edit category"}</h3><Input label="Name" value={name} onChange={e=>setName(e.target.value)}/><Input label="Slug (optional)" value={slug} onChange={e=>setSlug(e.target.value)}/>{error&&<p className="text-sm text-rose-300">{error}</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setEdit(null)}>Cancel</Button><Button disabled={busy||!name.trim()} onClick={save}>Save</Button></div></div></Modal>
    {detail&&<CategoryDetail category={detail} onClose={()=>setDetail(null)} onChanged={()=>{load();onChanged();}}/>}
  </div>;
}

function CategoryDetail({category,onClose,onChanged}:{category:Category;onClose:()=>void;onChanged:()=>void}) {
  const [providerId,setProviderId]=useState(""); const [q,setQ]=useState(""); const [status,setStatus]=useState(""); const [apiSource,setApiSource]=useState(""); const [page,setPage]=useState(1); const [data,setData]=useState<GameList|null>(null); const [selected,setSelected]=useState<number[]>([]); const [addProvider,setAddProvider]=useState(""); const [adding,setAdding]=useState(false); const [error,setError]=useState(""); const [addMode,setAddMode]=useState(false);
  const load=useCallback(async()=>{try{const p=new URLSearchParams({q,page:String(page),pageSize:"50"});if(!addMode)p.set("categoryId",String(category.id));if(providerId)p.set("providerId",providerId);if(status)p.set("status",status);if(apiSource)p.set("apiSource",apiSource);setData(await api<GameList>(`/api/admin/game-management/games?${p}`));}catch(e){setError(errMsg(e));}},[category.id,q,page,providerId,status,apiSource,addMode]);useEffect(()=>{const t=setTimeout(load,200);return()=>clearTimeout(t);},[load]);useEffect(()=>setSelected([]),[q,page,providerId,status,apiSource,addMode]);
  const assign=async(action:"add"|"remove",payload:Record<string,unknown>)=>{setAdding(true);setError("");try{const r=await api<{affected:number}>(`/api/admin/game-management/categories/${category.id}/games`,{body:{action,...payload}});setSelected([]);await load();onChanged();if(action==="add")alert(`${r.affected} game(s) added.`);}catch(e){setError(errMsg(e));}finally{setAdding(false);}};
  const addWholeProvider=async()=>{const provider=data?.providers.find(x=>String(x.value)===addProvider);if(!provider)return;if(!confirm(`Add all games from ${provider.label} to ${category.name}?`))return;await assign("add",{providerId:Number(addProvider),allProviderGames:true});};
  return <Modal open onClose={onClose} label={`${category.name} games`} maxWidth="md:max-w-6xl"><div className="space-y-4 p-4 md:p-6"><div className="flex flex-wrap items-start gap-3"><div className="mr-auto"><h2 className="text-xl font-semibold text-white">{category.name}</h2><p className="text-sm text-white/50">Removing a game only removes this category link.</p></div><Button size="sm" variant={addMode?"outline":"gold"} onClick={()=>setAddMode(!addMode)}>{addMode?"View category games":"Add games"}</Button></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><Input aria-label="Search games" placeholder="Search games…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><Select aria-label="Provider filter" value={providerId} onChange={e=>{setProviderId(e.target.value);setPage(1)}} options={[{value:"",label:addMode?"Choose provider first":"All providers"},...(data?.providers??[])]}/><Select aria-label="API filter" value={apiSource} onChange={e=>{setApiSource(e.target.value);setPage(1)}} options={[{value:"",label:"All APIs"},...(data?.apiSources??[])]}/><Select aria-label="Status filter" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} options={[{value:"",label:"All statuses"},{value:"active",label:"Active"},{value:"inactive",label:"Inactive"},{value:"maintenance",label:"Maintenance"}]}/><div className="flex gap-2"><Select aria-label="Add entire provider" value={addProvider} onChange={e=>setAddProvider(e.target.value)} options={[{value:"",label:"Choose provider"},...(data?.providers??[])]}/><Button size="sm" disabled={!addProvider||adding} onClick={addWholeProvider}>Add provider</Button></div></div>
    {selected.length>0&&<div className="flex flex-wrap items-center gap-2"><span className="mr-auto text-xs text-white/65">{selected.length} selected</span>{addMode?<Button size="xs" disabled={adding} onClick={()=>assign("add",{gameIds:selected})}>Add selected games</Button>:<Button size="xs" variant="outline" disabled={adding} onClick={()=>assign("remove",{gameIds:selected})}>Remove selected</Button>}</div>}{error&&<p className="text-sm text-rose-300">{error}</p>}{addMode&&!providerId?<Empty text="Choose a provider to browse its games."/>:!data?<Spinner/>:!data.items.length?<Empty text={addMode?"No games match this provider and filter.":"No games in this category match the filters."}/>:<><div className="flex items-center gap-2 text-xs text-white/50"><input type="checkbox" aria-label="Select all games on page" checked={data.items.length>0&&selected.length===data.items.length} onChange={()=>setSelected(selected.length===data.items.length?[]:data.items.map(g=>g.id))}/> Select page ({data.total.toLocaleString()} total)</div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{data.items.map(g=><label key={g.id} className="flex items-center gap-3 rounded-xl border border-white/10 p-2"><input type="checkbox" checked={selected.includes(g.id)} onChange={e=>setSelected(e.target.checked?[...selected,g.id]:selected.filter(id=>id!==g.id))}/><GameThumbnail src={g.thumbnail} name={g.name} className="h-12 w-12 rounded-lg object-cover" /><span className="min-w-0"><b className="block truncate text-sm text-white">{g.name}</b><small className="block truncate text-white/45">{g.providerName} · {g.apiSourceName}</small></span></label>)}</div><Pagination page={data.page} pageSize={data.pageSize} total={data.total} onPage={setPage}/></>}</div></Modal>;
}
